name: Release Docker Image
on:
  push:
    tags:
      - "*"

env:
  PackageOwner: hmbsbige
  PackageName: ${{ github.event.repository.name }}

jobs:
  release-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{  secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.PackageOwner }}/${{ env.PackageName }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
